theme: jekyll-theme-minimal
title: "Research proposal - Delphi study: Key opinions of healthcare workers to inform improved service delivery and reduce hospital admissions" 
description: "Draft invitation to clinicians for participation in research project which will include longitudinal analysis of regional hospital admissions and prescription of psychotropic drugs. The aim is standardisation of and widening access to multi-modal recovery programmes for depression and anxiety disorders (DADs) with or without comorbidities (triple focus - nutrition supplements, physio/clinical exercise prescription, resilience counselling)."
github: 
  is_user_page: false
