theme: jekyll-theme-minimal
title: "NHS Connecting for Health: Key opinions of healthcare workers to inform improved service delivery and reduce hospital admissions" 
description: "Draft invitation to participate in research project which will include longitudinal analysis of regional hospital admissions data as well as pre-(screening/risk analysis for exercise prescription) and post-treatment measures of VO2, resting metabolic rate, bioelectrical impedence analysis etc"
github: 
  is_user_page: false
